global_vars:
   - name: "kyzaconfig"
     type: script
     params:
        args:
           - deno
           - --quiet
           - eval
           - "import getFiles from 'https://deno.land/x/getfiles@v1.0.0/mod.ts'; import { dirname } from 'https://deno.land/std@0.164.0/path/mod.ts'; console.log(dirname(getFiles({ root: Deno.args[0], exclude: ['.git'] }).find((file) => file.name === '.kyzaconfig')?.realPath))"
           - --
           - "%CONFIG%"
