global_vars:
   - name: "kyzaconfig"
     type: script
     params:
        args:
           - deno
           - --quiet
           - eval
           - "import{basename,dirname,join}from'https://deno.land/std@@0.167.0/path/mod.ts';async function findFile(path,finder){const stack=await readDir(path);async function readDir(path){const files=[];for await(const file of Deno.readDir(path)){files.push(join(path,file.name))}return files}while(stack.length>0){const path1=stack.pop();const file=await Deno.stat(path1);if(file.isSymlink){stack.push(...await readDir(await Deno.readLink(path1)))}else if(file.isDirectory){try{stack.push(...await readDir(await Deno.readLink(path1)))}catch{stack.push(...await readDir(path1))}}else if(file.isFile){if(finder(path1,file)){return{path:path1,info:file}}}}}const foundPath=(await findFile(Deno.args[0],(path,info)=>info.isFile&&basename(path)==='.kyzaconfig'))?.path;const decoder=new TextDecoder('utf-8');if(foundPath!=null){const content=decoder.decode(Deno.readFileSync(foundPath));if(content==='root'){console.log(dirname(foundPath));Deno.exit()}else if(content==='config'||content==='match'){console.log(join(dirname(foundPath),'..'));Deno.exit()}}"
           - --
           - "%CONFIG%"
